esphome:
  name: light_c_19
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
  - ssid: "HOUSE"
    password: Welcome2
    priority: 2
  - ssid: "PEPPERTREES"
    password: Welcome2
    priority: 1
#  use_address: 192.168.1.124
#  use_address: 192.168.2.53

logger:

api:

ota:


web_server:
  port: 80

output:
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO14
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_white
    pin: GPIO5
#  - platform: esp8266_pwm
#    id: output_cold_white
#    pin: GPIO5
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO12

light:
  - platform: rgbw
    name: "Bedside Light"
    id: light_c_19
    red: output_red
    green: output_green
    blue: output_blue
    white: output_white
    #cold_white: output_cold_white
    #warm_white: output_warm_white
    #cold_white_color_temperature: 6536 K
    #warm_white_color_temperature: 2000 K
    # Ensure the light turns on by default if the physical switch is actuated.
    restore_mode: ALWAYS_ON
