# KOGAN POWER PLUG
substitutions:
  devicename: taras_fridge
  label: Taras Fridge

esphome:
  name: $devicename
  platform: ESP8266
  board: esp8285

wifi:
  networks:
#  - ssid: "HOUSE"
#    password: Welcome2
#    priority: 2
  - ssid: "PEPPERTREES"
    password: Welcome2 
    priority: 1
 # use_address: 192.168.2.56

# Enable logging
logger:

# Enable Web Server (optional)
web_server:
  port: 80
  
# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: ${label} Button
    on_press:
      - switch.toggle: relay

  - platform: status
    name: ${label} Status

switch:
  - platform: gpio
    id: green_led
    pin:
      number: GPIO13
      inverted: true
    restore_mode: ALWAYS_ON

  - platform: gpio
    name: ${label} 
    pin: GPIO14
    id: relay
    icon: mdi:television
    restore_mode: ALWAYS_ON

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current:
      name: ${label} Current
      unit_of_measurement: A
    voltage:
      name: ${label} Voltage
      unit_of_measurement: V
    power:
      id: ${devicename}_wattage
      name: ${label} Power
      unit_of_measurement: W
    current_resistor: "0.00087"   ### HIGHER VALUE GIVES LOWER WATTAGE
    voltage_divider: "2030"   ### LOWER VALUE GIVES LOWER VOLTAGE
    change_mode_every: 8
    update_interval: 5s
    
  - platform: total_daily_energy
    name: ${label} Daily Energy
    power_id: ${devicename}_wattage
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh
    
    
time:
  - platform: homeassistant
    id: homeassistant_time
